export const provinceCityMap =
{
  BUKIDNON: {
    BAUNGON: true,
    CABANGLASAN: true,
    'CITY OF MALAYBALAY': true,
    DAMULOG: true,
    DANGCAGAN: true,
    'DON CARLOS': true,
    'IMPASUG-ONG': true,
    KADINGILAN: true,
    KALILANGAN: true,
    KIBAWE: true,
    KITAOTAO: true,
    LANTAPAN: true,
    LIBONA: true,
    MALITBOG: true,
    'MANOLO FORTICH': true,
    MARAMAG: true,
    PANGANTUCAN: true,
    QUEZON: true,
    'SAN FERNANDO': true,
    SUMILAO: true,
    TALAKAG: true,
    'VALENCIA CITY': true
  },
  CAMIGUIN: {
    CATARMAN: true,
    GUINSILIBAN: true,
    MAHINOG: true,
    MAMBAJAO: true,
    SAGAY: true
  },
  'LANAO DEL NORTE': {
    BACOLOD: true,
    BALOI: true,
    BAROY: true,
    'ILIGAN CITY': true,
    KAPATAGAN: true,
    KAUSWAGAN: true,
    KOLAMBUGAN: true,
    LALA: true,
    LINAMON: true,
    MAGSAYSAY: true,
    MAIGO: true,
    MATUNGAO: true,
    MUNAI: true,
    NUNUNGAN: true,
    'PANTAO RAGAT': true,
    PANTAR: true,
    'POONA PIAGAPO': true,
    SALVADOR: true,
    SAPAD: true,
    'SULTAN NAGA DIMAPORO (KAROMATAN)': true,
    TAGOLOAN: true,
    TANGCAL: true,
    TUBOD: true
  },
  'MISAMIS OCCIDENTAL': {
    ALORAN: true,
    BALIANGAO: true,
    BONIFACIO: true,
    CALAMBA: true,
    CLARIN: true,
    CONCEPCION: true,
    'DON VICTORIANO CHIONGBIAN (DON MARIANO MARCOS)': true,
    JIMENEZ: true,
    'LOPEZ JAENA': true,
    'OROQUIETA CITY': true,
    'OZAMIS CITY': true,
    PANAON: true,
    PLARIDEL: true,
    'SAPANG DALAGA': true,
    SINACABAN: true,
    'TANGUB CITY': true,
    TUDELA: true
  },
  'MISAMIS ORIENTAL': {
    ALUBIJID: true,
    BALINGASAG: true,
    BALINGOAN: true,
    BINUANGAN: true,
    'CAGAYAN DE ORO CITY': true,
    CLAVERIA: true,
    'EL SALVADOR CITY': true,
    'GINGOOG CITY': true,
    GITAGUM: true,
    INITAO: true,
    JASAAN: true,
    KINOGUITAN: true,
    LAGONGLONG: true,
    LAGUINDINGAN: true,
    LIBERTAD: true,
    LUGAIT: true,
    'MAGSAYSAY (LINUGOS)': true,
    MANTICAO: true,
    MEDINA: true,
    NAAWAN: true,
    OPOL: true,
    SALAY: true,
    SUGBONGCOGON: true,
    TAGOLOAN: true,
    TALISAYAN: true,
    VILLANUEVA: true
  },
  'COMPOSTELA VALLEY': {
    COMPOSTELA: true,
    'LAAK (SAN VICENTE)': true,
    'MABINI (DOÑA ALICIA)': true,
    MACO: true,
    'MARAGUSAN (SAN MARIANO)': true,
    MAWAB: true,
    MONKAYO: true,
    MONTEVISTA: true,
    NABUNTURAN: true,
    'NEW BATAAN': true,
    PANTUKAN: true
  },
  'DAVAO (DAVAO DEL NORTE)': {
    'ASUNCION (SAUG)': true,
    'BRAULIO E. DUJALI': true,
    CARMEN: true,
    'CITY OF TAGUM': true,
    'ISLAND GARDEN CITY OF SAMAL': true,
    KAPALONG: true,
    'NEW CORELLA': true,
    'PANABO CITY': true,
    'SAN ISIDRO': true,
    'SANTO TOMAS': true,
    TALAINGOD: true
  },
  'DAVAO DEL SUR': {
    BANSALAN: true,
    'DAVAO CITY': true,
    'DIGOS CITY': true,
    HAGONOY: true,
    KIBLAWAN: true,
    MAGSAYSAY: true,
    MALALAG: true,
    MATANAO: true,
    PADADA: true,
    'SANTA CRUZ': true,
    SULOP: true
  },
  'DAVAO OCCIDENTAL': {
    'DON MARCELINO': true,
    'JOSE ABAD SANTOS (TRINIDAD)': true,
    MALITA: true,
    'SANTA MARIA': true,
    SARANGANI: true
  },
  'DAVAO ORIENTAL': {
    BAGANGA: true,
    BANAYBANAY: true,
    BOSTON: true,
    CARAGA: true,
    CATEEL: true,
    'GOVERNOR GENEROSO': true,
    LUPON: true,
    MANAY: true,
    'MATI CITY': true,
    'SAN ISIDRO': true,
    TARRAGONA: true
  },
  'COTABATO (NORTH COT.)': {
    ALAMADA: true,
    ALEOSAN: true,
    ANTIPAS: true,
    ARAKAN: true,
    BANISILAN: true,
    CARMEN: true,
    'CITY OF KIDAPAWAN': true,
    KABACAN: true,
    LIBUNGAN: true,
    "M'LANG": true,
    MAGPET: true,
    MAKILALA: true,
    MATALAM: true,
    MIDSAYAP: true,
    PIGKAWAYAN: true,
    PIKIT: true,
    'PRESIDENT ROXAS': true,
    TULUNAN: true
  },
  SARANGANI: {
    ALABEL: true,
    GLAN: true,
    KIAMBA: true,
    MAASIM: true,
    MAITUM: true,
    MALAPATAN: true,
    MALUNGON: true
  },
  'SOUTH COTABATO': {
    BANGA: true,
    'GENERAL SANTOS CITY (DADIANGAS)': true,
    'KORONADAL CITY': true,
    'LAKE SEBU': true,
    NORALA: true,
    POLOMOLOK: true,
    'SANTO NIÑO': true,
    SURALLAH: true,
    'T`BOLI': true,
    TAMPAKAN: true,
    TANTANGAN: true,
    TUPI: true
  },
  'SULTAN KUDARAT': {
    BAGUMBAYAN: true,
    COLUMBIO: true,
    ESPERANZA: true,
    ISULAN: true,
    KALAMANSIG: true,
    'LAMBAYONG (MARIANO MARCOS)': true,
    LEBAK: true,
    LUTAYAN: true,
    PALIMBANG: true,
    'PRESIDENT QUIRINO': true,
    'SEN. NINOY AQUINO': true,
    'TACURONG CITY': true
  },
  'AGUSAN DEL NORTE': {
    BUENAVISTA: true,
    'BUTUAN CITY': true,
    'CABADBARAN CITY': true,
    CARMEN: true,
    JABONGA: true,
    KITCHARAO: true,
    'LAS NIEVES': true,
    MAGALLANES: true,
    NASIPIT: true,
    'REMEDIOS T. ROMUALDEZ': true,
    SANTIAGO: true,
    TUBAY: true
  },
  'AGUSAN DEL SUR': {
    'BAYUGAN CITY': true,
    BUNAWAN: true,
    ESPERANZA: true,
    'LA PAZ': true,
    LORETO: true,
    PROSPERIDAD: true,
    ROSARIO: true,
    'SAN FRANCISCO': true,
    'SAN LUIS': true,
    'SANTA JOSEFA': true,
    SIBAGAT: true,
    TALACOGON: true,
    TRENTO: true,
    VERUELA: true
  },
  'DINAGAT ISLANDS': {
    'BASILISA (RIZAL)': true,
    CAGDIANAO: true,
    DINAGAT: true,
    'LIBJO (ALBOR)': true,
    LORETO: true,
    'SAN JOSE': true,
    TUBAJON: true
  },
  'SURIGAO DEL NORTE': {
    ALEGRIA: true,
    BACUAG: true,
    BURGOS: true,
    CLAVER: true,
    DAPA: true,
    'DEL CARMEN': true,
    'GENERAL LUNA': true,
    GIGAQUIT: true,
    MAINIT: true,
    MALIMONO: true,
    PILAR: true,
    PLACER: true,
    'SAN BENITO': true,
    'SAN FRANCISCO (ANAO-AON)': true,
    'SAN ISIDRO': true,
    'SANTA MONICA (SAPAO)': true,
    SISON: true,
    SOCORRO: true,
    'SURIGAO CITY': true,
    'TAGANA-AN': true,
    TUBOD: true
  },
  'SURIGAO DEL SUR': {
    BAROBO: true,
    BAYABAS: true,
    'BISLIG CITY': true,
    CAGWAIT: true,
    CANTILAN: true,
    CARMEN: true,
    CARRASCAL: true,
    CORTES: true,
    HINATUAN: true,
    LANUZA: true,
    LIANGA: true,
    LINGIG: true,
    MADRID: true,
    MARIHATAG: true,
    'SAN AGUSTIN': true,
    'SAN MIGUEL': true,
    TAGBINA: true,
    TAGO: true,
    'TANDAG CITY': true
  },
  'ILOCOS NORTE': {
    ADAMS: true,
    BACARRA: true,
    BADOC: true,
    BANGUI: true,
    'BANNA (ESPIRITU)': true,
    'BATAC CITY': true,
    BURGOS: true,
    CARASI: true,
    CURRIMAO: true,
    DINGRAS: true,
    DUMALNEG: true,
    'LAOAG CITY': true,
    MARCOS: true,
    'NUEVA ERA': true,
    PAGUDPUD: true,
    PAOAY: true,
    PASUQUIN: true,
    PIDDIG: true,
    PINILI: true,
    'SAN NICOLAS': true,
    SARRAT: true,
    SOLSONA: true,
    VINTAR: true
  },
  'ILOCOS SUR': {
    ALILEM: true,
    BANAYOYO: true,
    BANTAY: true,
    BURGOS: true,
    CABUGAO: true,
    'CANDON CITY': true,
    CAOAYAN: true,
    CERVANTES: true,
    GALIMUYOD: true,
    'GREGORIO DEL PILAR (CONCEPCION)': true,
    LIDLIDDA: true,
    MAGSINGAL: true,
    NAGBUKEL: true,
    NARVACAN: true,
    'QUIRINO (ANGKAKI)': true,
    'SALCEDO (BAUGEN)': true,
    'SAN EMILIO': true,
    'SAN ESTEBAN': true,
    'SAN ILDEFONSO': true,
    'SAN JUAN (LAPOG)': true,
    'SAN VICENTE': true,
    SANTA: true,
    'SANTA CATALINA': true,
    'SANTA CRUZ': true,
    'SANTA LUCIA': true,
    'SANTA MARIA': true,
    SANTIAGO: true,
    'SANTO DOMINGO': true,
    SIGAY: true,
    SINAIT: true,
    SUGPON: true,
    SUYO: true,
    TAGUDIN: true,
    'VIGAN CITY': true
  },
  'LA UNION': {
    AGOO: true,
    ARINGAY: true,
    BACNOTAN: true,
    BAGULIN: true,
    BALAOAN: true,
    BANGAR: true,
    BAUANG: true,
    BURGOS: true,
    CABA: true,
    'CITY OF SAN FERNANDO': true,
    LUNA: true,
    NAGUILIAN: true,
    PUGO: true,
    ROSARIO: true,
    'SAN GABRIEL': true,
    'SAN JUAN': true,
    'SANTO TOMAS': true,
    SANTOL: true,
    SUDIPEN: true,
    TUBAO: true
  },
  PANGASINAN: {
    AGNO: true,
    AGUILAR: true,
    'ALAMINOS CITY': true,
    ALCALA: true,
    ANDA: true,
    ASINGAN: true,
    BALUNGAO: true,
    BANI: true,
    BASISTA: true,
    BAUTISTA: true,
    BAYAMBANG: true,
    BINALONAN: true,
    BINMALEY: true,
    BOLINAO: true,
    BUGALLON: true,
    BURGOS: true,
    CALASIAO: true,
    'DAGUPAN CITY': true,
    DASOL: true,
    INFANTA: true,
    LABRADOR: true,
    LAOAC: true,
    LINGAYEN: true,
    MABINI: true,
    MALASIQUI: true,
    MANAOAG: true,
    MANGALDAN: true,
    MANGATAREM: true,
    MAPANDAN: true,
    NATIVIDAD: true,
    POZORRUBIO: true,
    ROSALES: true,
    'SAN CARLOS CITY': true,
    'SAN FABIAN': true,
    'SAN JACINTO': true,
    'SAN MANUEL': true,
    'SAN NICOLAS': true,
    'SAN QUINTIN': true,
    'SANTA BARBARA': true,
    'SANTA MARIA': true,
    'SANTO TOMAS': true,
    SISON: true,
    SUAL: true,
    TAYUG: true,
    UMINGAN: true,
    URBIZTONDO: true,
    'URDANETA CITY': true,
    VILLASIS: true
  },
  BATANES: {
    BASCO: true,
    ITBAYAT: true,
    IVANA: true,
    MAHATAO: true,
    SABTANG: true,
    UYUGAN: true
  },
  CAGAYAN: {
    ABULUG: true,
    ALCALA: true,
    ALLACAPAN: true,
    AMULUNG: true,
    APARRI: true,
    BAGGAO: true,
    BALLESTEROS: true,
    BUGUEY: true,
    CALAYAN: true,
    CAMALANIUGAN: true,
    CLAVERIA: true,
    ENRILE: true,
    GATTARAN: true,
    GONZAGA: true,
    IGUIG: true,
    'LAL-LO': true,
    LASAM: true,
    PAMPLONA: true,
    PEÑABLANCA: true,
    PIAT: true,
    RIZAL: true,
    'SANCHEZ-MIRA': true,
    'SANTA ANA': true,
    'SANTA PRAXEDES': true,
    'SANTA TERESITA': true,
    'SANTO NIÑO (FAIRE)': true,
    SOLANA: true,
    TUAO: true,
    'TUGUEGARAO CITY': true
  },
  ISABELA: {
    ALICIA: true,
    ANGADANAN: true,
    AURORA: true,
    'BENITO SOLIVEN': true,
    BURGOS: true,
    CABAGAN: true,
    CABATUAN: true,
    'CAUAYAN CITY': true,
    'CITY OF SANTIAGO': true,
    CORDON: true,
    'DELFIN ALBANO (MAGSAYSAY)': true,
    DINAPIGUE: true,
    DIVILACAN: true,
    ECHAGUE: true,
    GAMU: true,
    'ILAGAN CITY': true,
    JONES: true,
    LUNA: true,
    MACONACON: true,
    MALLIG: true,
    NAGUILIAN: true,
    PALANAN: true,
    QUEZON: true,
    QUIRINO: true,
    RAMON: true,
    'REINA MERCEDES': true,
    ROXAS: true,
    'SAN AGUSTIN': true,
    'SAN GUILLERMO': true,
    'SAN ISIDRO': true,
    'SAN MANUEL': true,
    'SAN MARIANO': true,
    'SAN MATEO': true,
    'SAN PABLO': true,
    'SANTA MARIA': true,
    'SANTO TOMAS': true,
    TUMAUINI: true
  },
  'NUEVA VIZCAYA': {
    'ALFONSO CASTANEDA': true,
    AMBAGUIO: true,
    ARITAO: true,
    BAGABAG: true,
    BAMBANG: true,
    BAYOMBONG: true,
    DIADI: true,
    'DUPAX DEL NORTE': true,
    'DUPAX DEL SUR': true,
    KASIBU: true,
    KAYAPA: true,
    QUEZON: true,
    'SANTA FE': true,
    SOLANO: true,
    VILLAVERDE: true
  },
  QUIRINO: {
    AGLIPAY: true,
    CABARROGUIS: true,
    DIFFUN: true,
    MADDELA: true,
    NAGTIPUNAN: true,
    SAGUDAY: true
  },
  AURORA: {
    BALER: true,
    CASIGURAN: true,
    DILASAG: true,
    DINALUNGAN: true,
    DINGALAN: true,
    DIPACULAO: true,
    'MARIA AURORA': true,
    'SAN LUIS': true
  },
  BATAAN: {
    ABUCAY: true,
    BAGAC: true,
    'BALANGA CITY': true,
    DINALUPIHAN: true,
    HERMOSA: true,
    LIMAY: true,
    MARIVELES: true,
    MORONG: true,
    ORANI: true,
    ORION: true,
    PILAR: true,
    SAMAL: true
  },
  BULACAN: {
    ANGAT: true,
    'BALAGTAS (BIGAA)': true,
    BALIUAG: true,
    BOCAUE: true,
    BULACAN: true,
    BUSTOS: true,
    CALUMPIT: true,
    'DOÑA REMEDIOS TRINIDAD': true,
    GUIGUINTO: true,
    HAGONOY: true,
    'MALOLOS CITY': true,
    MARILAO: true,
    'MEYCAUAYAN CITY': true,
    NORZAGARAY: true,
    OBANDO: true,
    PANDI: true,
    PAOMBONG: true,
    PLARIDEL: true,
    PULILAN: true,
    'SAN ILDEFONSO': true,
    'SAN JOSE DEL MONTE CITY': true,
    'SAN MIGUEL': true,
    'SAN RAFAEL': true,
    'SANTA MARIA': true
  },
  'NUEVA ECIJA': {
    ALIAGA: true,
    BONGABON: true,
    'CABANATUAN CITY': true,
    CABIAO: true,
    CARRANGLAN: true,
    CUYAPO: true,
    'GABALDON (BITULOK AND SABANI)': true,
    'GAPAN CITY': true,
    'GENERAL MAMERTO NATIVIDAD': true,
    'GENERAL TINIO (PAPAYA)': true,
    GUIMBA: true,
    JAEN: true,
    LAUR: true,
    LICAB: true,
    LLANERA: true,
    LUPAO: true,
    NAMPICUAN: true,
    'PALAYAN CITY': true,
    PANTABANGAN: true,
    PEÑARANDA: true,
    QUEZON: true,
    RIZAL: true,
    'SAN ANTONIO': true,
    'SAN ISIDRO': true,
    'SAN JOSE CITY': true,
    'SAN LEONARDO': true,
    'SANTA ROSA': true,
    'SANTO DOMINGO': true,
    'SCIENCE CITY OF MUÑOZ': true,
    TALAVERA: true,
    TALUGTUG: true,
    ZARAGOZA: true
  },
  PAMPANGA: {
    'ANGELES CITY': true,
    APALIT: true,
    ARAYAT: true,
    BACOLOR: true,
    CANDABA: true,
    FLORIDABLANCA: true,
    GUAGUA: true,
    LUBAO: true,
    'MABALACAT CITY': true,
    MACABEBE: true,
    MAGALANG: true,
    MASANTOL: true,
    MEXICO: true,
    MINALIN: true,
    PORAC: true,
    'SAN FERNANDO CITY': true,
    'SAN LUIS': true,
    'SAN SIMON': true,
    'SANTA ANA': true,
    'SANTA RITA': true,
    'SANTO TOMAS': true,
    'SASMUAN (SEXMOAN)': true
  },
  TARLAC: {
    ANAO: true,
    BAMBAN: true,
    CAMILING: true,
    CAPAS: true,
    'CITY OF TARLAC': true,
    CONCEPCION: true,
    GERONA: true,
    'LA PAZ': true,
    MAYANTOC: true,
    MONCADA: true,
    PANIQUI: true,
    PURA: true,
    RAMOS: true,
    'SAN CLEMENTE': true,
    'SAN JOSE': true,
    'SAN MANUEL': true,
    'SANTA IGNACIA': true,
    VICTORIA: true
  },
  ZAMBALES: {
    BOTOLAN: true,
    CABANGAN: true,
    CANDELARIA: true,
    CASTILLEJOS: true,
    IBA: true,
    MASINLOC: true,
    'OLONGAPO CITY': true,
    PALAUIG: true,
    'SAN ANTONIO': true,
    'SAN FELIPE': true,
    'SAN MARCELINO': true,
    'SAN NARCISO': true,
    'SANTA CRUZ': true,
    SUBIC: true
  },
  BATANGAS: {
    AGONCILLO: true,
    ALITAGTAG: true,
    BALAYAN: true,
    BALETE: true,
    'BATANGAS CITY': true,
    BAUAN: true,
    CALACA: true,
    CALATAGAN: true,
    CUENCA: true,
    IBAAN: true,
    LAUREL: true,
    LEMERY: true,
    LIAN: true,
    'LIPA CITY': true,
    LOBO: true,
    MABINI: true,
    MALVAR: true,
    'MATAAS NA KAHOY': true,
    NASUGBU: true,
    'PADRE GARCIA': true,
    ROSARIO: true,
    'SAN JOSE': true,
    'SAN JUAN': true,
    'SAN LUIS': true,
    'SAN NICOLAS': true,
    'SAN PASCUAL': true,
    'SANTA TERESITA': true,
    'SANTO TOMAS': true,
    TAAL: true,
    TALISAY: true,
    'TANAUAN CITY': true,
    TAYSAN: true,
    TINGLOY: true,
    TUY: true
  },
  CAVITE: {
    ALFONSO: true,
    AMADEO: true,
    'BACOOR CITY': true,
    CARMONA: true,
    'CAVITE CITY': true,
    'DASMARIÑAS CITY': true,
    'GEN. MARIANO ALVAREZ': true,
    'GENERAL EMILIO AGUINALDO': true,
    'GENERAL TRIAS CITY': true,
    'IMUS CITY': true,
    INDANG: true,
    KAWIT: true,
    MAGALLANES: true,
    MARAGONDON: true,
    'MENDEZ (MENDEZ-NUÑEZ)': true,
    NAIC: true,
    NOVELETA: true,
    ROSARIO: true,
    SILANG: true,
    'TAGAYTAY CITY': true,
    TANZA: true,
    TERNATE: true,
    'TRECE MARTIRES CITY': true
  },
  LAGUNA: {
    ALAMINOS: true,
    BAY: true,
    'CABUYAO CITY': true,
    'CALAMBA CITY': true,
    CALAUAN: true,
    CAVINTI: true,
    'CITY OF BIÑAN': true,
    FAMY: true,
    KALAYAAN: true,
    LILIW: true,
    'LOS BAÑOS': true,
    LUISIANA: true,
    LUMBAN: true,
    MABITAC: true,
    MAGDALENA: true,
    MAJAYJAY: true,
    NAGCARLAN: true,
    PAETE: true,
    PAGSANJAN: true,
    PAKIL: true,
    PANGIL: true,
    PILA: true,
    RIZAL: true,
    'SAN PABLO CITY': true,
    'SAN PEDRO CITY': true,
    'SANTA CRUZ': true,
    'SANTA MARIA': true,
    'SANTA ROSA CITY': true,
    SINILOAN: true,
    VICTORIA: true
  },
  QUEZON: {
    AGDANGAN: true,
    ALABAT: true,
    ATIMONAN: true,
    BUENAVISTA: true,
    BURDEOS: true,
    CALAUAG: true,
    CANDELARIA: true,
    CATANAUAN: true,
    DOLORES: true,
    'GENERAL LUNA': true,
    'GENERAL NAKAR': true,
    GUINAYANGAN: true,
    GUMACA: true,
    INFANTA: true,
    JOMALIG: true,
    LOPEZ: true,
    LUCBAN: true,
    'LUCENA CITY': true,
    MACALELON: true,
    MAUBAN: true,
    MULANAY: true,
    'PADRE BURGOS': true,
    PAGBILAO: true,
    PANUKULAN: true,
    PATNANUNGAN: true,
    PEREZ: true,
    PITOGO: true,
    PLARIDEL: true,
    POLILLO: true,
    QUEZON: true,
    REAL: true,
    SAMPALOC: true,
    'SAN ANDRES': true,
    'SAN ANTONIO': true,
    'SAN FRANCISCO (AURORA)': true,
    'SAN NARCISO': true,
    SARIAYA: true,
    TAGKAWAYAN: true,
    'TAYABAS CITY': true,
    TIAONG: true,
    UNISAN: true
  },
  RIZAL: {
    ANGONO: true,
    BARAS: true,
    BINANGONAN: true,
    CAINTA: true,
    CARDONA: true,
    'CITY OF ANTIPOLO': true,
    'JALA-JALA': true,
    MORONG: true,
    PILILLA: true,
    'RODRIGUEZ (MONTALBAN)': true,
    'SAN MATEO': true,
    TANAY: true,
    TAYTAY: true,
    TERESA: true
  },
  MARINDUQUE: {
    BOAC: true,
    BUENAVISTA: true,
    GASAN: true,
    MOGPOG: true,
    'SANTA CRUZ': true,
    TORRIJOS: true
  },
  'OCCIDENTAL MINDORO': {
    'ABRA DE ILOG': true,
    CALINTAAN: true,
    LOOC: true,
    LUBANG: true,
    MAGSAYSAY: true,
    MAMBURAO: true,
    PALUAN: true,
    RIZAL: true,
    SABLAYAN: true,
    'SAN JOSE': true,
    'SANTA CRUZ': true
  },
  'ORIENTAL MINDORO': {
    BACO: true,
    BANSUD: true,
    BONGABONG: true,
    'BULALACAO (SAN PEDRO)': true,
    'CITY OF CALAPAN': true,
    GLORIA: true,
    MANSALAY: true,
    NAUJAN: true,
    PINAMALAYAN: true,
    POLA: true,
    'PUERTO GALERA': true,
    ROXAS: true,
    'SAN TEODORO': true,
    SOCORRO: true,
    VICTORIA: true
  },
  PALAWAN: {
    ABORLAN: true,
    AGUTAYA: true,
    ARACELI: true,
    BALABAC: true,
    BATARAZA: true,
    "BROOKE'S POINT": true,
    BUSUANGA: true,
    CAGAYANCILLO: true,
    CORON: true,
    CULION: true,
    CUYO: true,
    DUMARAN: true,
    'EL NIDO (BACUIT)': true,
    KALAYAAN: true,
    LINAPACAN: true,
    MAGSAYSAY: true,
    NARRA: true,
    'PUERTO PRINCESA CITY': true,
    QUEZON: true,
    'RIZAL (MARCOS)': true,
    ROXAS: true,
    'SAN VICENTE': true,
    'SOFRONIO ESPAÑOLA': true,
    TAYTAY: true
  },
  ROMBLON: {
    ALCANTARA: true,
    BANTON: true,
    CAJIDIOCAN: true,
    CALATRAVA: true,
    CONCEPCION: true,
    CORCUERA: true,
    FERROL: true,
    LOOC: true,
    MAGDIWANG: true,
    ODIONGAN: true,
    ROMBLON: true,
    'SAN AGUSTIN': true,
    'SAN ANDRES': true,
    'SAN FERNANDO': true,
    'SAN JOSE': true,
    'SANTA FE': true,
    'SANTA MARIA (IMELDA)': true
  },
  ALBAY: {
    BACACAY: true,
    CAMALIG: true,
    'CITY OF LIGAO': true,
    'DARAGA (LOCSIN)': true,
    GUINOBATAN: true,
    JOVELLAR: true,
    'LEGAZPI CITY': true,
    LIBON: true,
    MALILIPOT: true,
    MALINAO: true,
    MANITO: true,
    OAS: true,
    'PIO DURAN': true,
    POLANGUI: true,
    'RAPU-RAPU': true,
    'SANTO DOMINGO (LIBOG)': true,
    'TABACO CITY': true,
    TIWI: true
  },
  'CAMARINES NORTE': {
    BASUD: true,
    CAPALONGA: true,
    DAET: true,
    'JOSE PANGANIBAN': true,
    LABO: true,
    MERCEDES: true,
    PARACALE: true,
    'SAN LORENZO RUIZ (IMELDA)': true,
    'SAN VICENTE': true,
    'SANTA ELENA': true,
    TALISAY: true,
    VINZONS: true
  },
  'CAMARINES SUR': {
    BAAO: true,
    BALATAN: true,
    BATO: true,
    BOMBON: true,
    BUHI: true,
    BULA: true,
    CABUSAO: true,
    CALABANGA: true,
    CAMALIGAN: true,
    CANAMAN: true,
    CARAMOAN: true,
    'DEL GALLEGO': true,
    GAINZA: true,
    GARCHITORENA: true,
    GOA: true,
    'IRIGA CITY': true,
    LAGONOY: true,
    LIBMANAN: true,
    LUPI: true,
    MAGARAO: true,
    MILAOR: true,
    MINALABAC: true,
    NABUA: true,
    'NAGA CITY': true,
    OCAMPO: true,
    PAMPLONA: true,
    PASACAO: true,
    PILI: true,
    'PRESENTACION (PARUBCAN)': true,
    RAGAY: true,
    SAGÑAY: true,
    'SAN FERNANDO': true,
    'SAN JOSE': true,
    SIPOCOT: true,
    SIRUMA: true,
    TIGAON: true,
    TINAMBAC: true
  },
  CATANDUANES: {
    BAGAMANOC: true,
    BARAS: true,
    BATO: true,
    CARAMORAN: true,
    GIGMOTO: true,
    PANDAN: true,
    'PANGANIBAN (PAYO)': true,
    'SAN ANDRES (CALOLBON)': true,
    'SAN MIGUEL': true,
    VIGA: true,
    VIRAC: true
  },
  MASBATE: {
    AROROY: true,
    BALENO: true,
    BALUD: true,
    BATUAN: true,
    CATAINGAN: true,
    CAWAYAN: true,
    CLAVERIA: true,
    DIMASALANG: true,
    ESPERANZA: true,
    MANDAON: true,
    'MASBATE CITY': true,
    MILAGROS: true,
    MOBO: true,
    MONREAL: true,
    PALANAS: true,
    'PIO V. CORPUZ (LIMBUHAN)': true,
    PLACER: true,
    'SAN FERNANDO': true,
    'SAN JACINTO': true,
    'SAN PASCUAL': true,
    USON: true
  },
  SORSOGON: {
    BARCELONA: true,
    BULAN: true,
    BULUSAN: true,
    CASIGURAN: true,
    CASTILLA: true,
    DONSOL: true,
    GUBAT: true,
    IROSIN: true,
    JUBAN: true,
    MAGALLANES: true,
    MATNOG: true,
    PILAR: true,
    'PRIETO DIAZ': true,
    'SANTA MAGDALENA': true,
    'SORSOGON CITY': true
  },
  AKLAN: {
    ALTAVAS: true,
    BALETE: true,
    BANGA: true,
    BATAN: true,
    BURUANGA: true,
    IBAJAY: true,
    KALIBO: true,
    LEZO: true,
    LIBACAO: true,
    MADALAG: true,
    MAKATO: true,
    MALAY: true,
    MALINAO: true,
    NABAS: true,
    'NEW WASHINGTON': true,
    NUMANCIA: true,
    TANGALAN: true
  },
  ANTIQUE: {
    'ANINI-Y': true,
    BARBAZA: true,
    BELISON: true,
    BUGASONG: true,
    CALUYA: true,
    CULASI: true,
    HAMTIC: true,
    'LAUA-AN': true,
    LIBERTAD: true,
    PANDAN: true,
    PATNONGON: true,
    'SAN JOSE': true,
    'SAN REMIGIO': true,
    SEBASTE: true,
    SIBALOM: true,
    TIBIAO: true,
    'TOBIAS FORNIER (DAO)': true,
    VALDERRAMA: true
  },
  CAPIZ: {
    CUARTERO: true,
    DAO: true,
    DUMALAG: true,
    DUMARAO: true,
    IVISAN: true,
    JAMINDAN: true,
    'MA-AYON': true,
    MAMBUSAO: true,
    PANAY: true,
    PANITAN: true,
    PILAR: true,
    PONTEVEDRA: true,
    'PRESIDENT ROXAS': true,
    'ROXAS CITY': true,
    'SAPI-AN': true,
    SIGMA: true,
    TAPAZ: true
  },
  GUIMARAS: {
    BUENAVISTA: true,
    JORDAN: true,
    'NUEVA VALENCIA': true,
    'SAN LORENZO': true,
    SIBUNAG: true
  },
  ILOILO: {
    AJUY: true,
    ALIMODIAN: true,
    ANILAO: true,
    BADIANGAN: true,
    BALASAN: true,
    BANATE: true,
    'BAROTAC NUEVO': true,
    'BAROTAC VIEJO': true,
    BATAD: true,
    BINGAWAN: true,
    CABATUAN: true,
    CALINOG: true,
    CARLES: true,
    'CITY OF PASSI': true,
    CONCEPCION: true,
    DINGLE: true,
    DUEÑAS: true,
    DUMANGAS: true,
    ESTANCIA: true,
    GUIMBAL: true,
    IGBARAS: true,
    'ILOILO CITY': true,
    JANIUAY: true,
    LAMBUNAO: true,
    LEGANES: true,
    LEMERY: true,
    LEON: true,
    MAASIN: true,
    MIAGAO: true,
    MINA: true,
    'NEW LUCENA': true,
    OTON: true,
    PAVIA: true,
    POTOTAN: true,
    'SAN DIONISIO': true,
    'SAN ENRIQUE': true,
    'SAN JOAQUIN': true,
    'SAN MIGUEL': true,
    'SAN RAFAEL': true,
    'SANTA BARBARA': true,
    SARA: true,
    TIGBAUAN: true,
    TUBUNGAN: true,
    ZARRAGA: true
  },
  'NEGROS OCCIDENTAL': {
    'BACOLOD CITY': true,
    'BAGO CITY': true,
    BINALBAGAN: true,
    'CADIZ CITY': true,
    CALATRAVA: true,
    CANDONI: true,
    CAUAYAN: true,
    'ENRIQUE B. MAGALONA (SARAVIA)': true,
    'ESCALANTE CITY': true,
    'HIMAMAYLAN CITY': true,
    HINIGARAN: true,
    'HINOBA-AN (ASIA)': true,
    ILOG: true,
    ISABELA: true,
    'KABANKALAN CITY': true,
    'LA CARLOTA CITY': true,
    'LA CASTELLANA': true,
    MANAPLA: true,
    'MOISES PADILLA (MAGALLON)': true,
    MURCIA: true,
    PONTEVEDRA: true,
    PULUPANDAN: true,
    'SAGAY CITY': true,
    'SALVADOR BENEDICTO': true,
    'SAN CARLOS CITY': true,
    'SAN ENRIQUE': true,
    'SILAY CITY': true,
    'SIPALAY CITY': true,
    'TALISAY CITY': true,
    TOBOSO: true,
    VALLADOLID: true,
    'VICTORIAS CITY': true
  },
  BOHOL: {
    ALBURQUERQUE: true,
    ALICIA: true,
    ANDA: true,
    ANTEQUERA: true,
    BACLAYON: true,
    BALILIHAN: true,
    BATUAN: true,
    'BIEN UNIDO': true,
    BILAR: true,
    BUENAVISTA: true,
    CALAPE: true,
    CANDIJAY: true,
    CARMEN: true,
    CATIGBIAN: true,
    CLARIN: true,
    CORELLA: true,
    CORTES: true,
    DAGOHOY: true,
    DANAO: true,
    DAUIS: true,
    DIMIAO: true,
    DUERO: true,
    'GARCIA HERNANDEZ': true,
    GUINDULMAN: true,
    INABANGA: true,
    JAGNA: true,
    JETAFE: true,
    LILA: true,
    LOAY: true,
    LOBOC: true,
    LOON: true,
    MABINI: true,
    MARIBOJOC: true,
    PANGLAO: true,
    PILAR: true,
    'PRES. CARLOS P. GARCIA (PITOGO)': true,
    'SAGBAYAN (BORJA)': true,
    'SAN ISIDRO': true,
    'SAN MIGUEL': true,
    SEVILLA: true,
    'SIERRA BULLONES': true,
    SIKATUNA: true,
    'TAGBILARAN CITY': true,
    TALIBON: true,
    TRINIDAD: true,
    TUBIGON: true,
    UBAY: true,
    VALENCIA: true
  },
  CEBU: {
    ALCANTARA: true,
    ALCOY: true,
    ALEGRIA: true,
    ALOGUINSAN: true,
    ARGAO: true,
    ASTURIAS: true,
    BADIAN: true,
    BALAMBAN: true,
    BANTAYAN: true,
    BARILI: true,
    'BOGO CITY': true,
    BOLJOON: true,
    BORBON: true,
    'CARCAR CITY': true,
    CARMEN: true,
    CATMON: true,
    'CEBU CITY': true,
    COMPOSTELA: true,
    CONSOLACION: true,
    CORDOBA: true,
    DAANBANTAYAN: true,
    DALAGUETE: true,
    'DANAO CITY': true,
    DUMANJUG: true,
    GINATILAN: true,
    'LAPU-LAPU CITY (OPON)': true,
    LILOAN: true,
    MADRIDEJOS: true,
    MALABUYOC: true,
    'MANDAUE CITY': true,
    MEDELLIN: true,
    MINGLANILLA: true,
    MOALBOAL: true,
    'NAGA CITY': true,
    OSLOB: true,
    PILAR: true,
    PINAMUNGAHAN: true,
    PORO: true,
    RONDA: true,
    SAMBOAN: true,
    'SAN FERNANDO': true,
    'SAN FRANCISCO': true,
    'SAN REMIGIO': true,
    'SANTA FE': true,
    SANTANDER: true,
    SIBONGA: true,
    SOGOD: true,
    TABOGON: true,
    TABUELAN: true,
    'TALISAY CITY': true,
    'TOLEDO CITY': true,
    TUBURAN: true,
    TUDELA: true
  },
  'NEGROS ORIENTAL': {
    'AMLAN (AYUQUITAN)': true,
    AYUNGON: true,
    BACONG: true,
    'BAIS CITY': true,
    BASAY: true,
    'BAYAWAN CITY (TULONG)': true,
    'BINDOY (PAYABON)': true,
    'CANLAON CITY': true,
    DAUIN: true,
    'DUMAGUETE CITY': true,
    'GUIHULNGAN CITY': true,
    JIMALALUD: true,
    'LA LIBERTAD': true,
    MABINAY: true,
    MANJUYOD: true,
    PAMPLONA: true,
    'SAN JOSE': true,
    'SANTA CATALINA': true,
    SIATON: true,
    SIBULAN: true,
    'TANJAY CITY': true,
    TAYASAN: true,
    'VALENCIA (LUZURRIAGA)': true,
    VALLEHERMOSO: true,
    ZAMBOANGUITA: true
  },
  SIQUIJOR: {
    'ENRIQUE VILLANUEVA': true,
    LARENA: true,
    LAZI: true,
    MARIA: true,
    'SAN JUAN': true,
    SIQUIJOR: true
  },
  BILIRAN: {
    ALMERIA: true,
    BILIRAN: true,
    CABUCGAYAN: true,
    CAIBIRAN: true,
    CULABA: true,
    KAWAYAN: true,
    MARIPIPI: true,
    NAVAL: true
  },
  'EASTERN SAMAR': {
    ARTECHE: true,
    BALANGIGA: true,
    BALANGKAYAN: true,
    'BORONGAN CITY': true,
    'CAN-AVID': true,
    DOLORES: true,
    'GENERAL MACARTHUR': true,
    GIPORLOS: true,
    GUIUAN: true,
    HERNANI: true,
    JIPAPAD: true,
    LAWAAN: true,
    LLORENTE: true,
    MASLOG: true,
    MAYDOLONG: true,
    MERCEDES: true,
    ORAS: true,
    QUINAPONDAN: true,
    SALCEDO: true,
    'SAN JULIAN': true,
    'SAN POLICARPO': true,
    SULAT: true,
    TAFT: true
  },
  LEYTE: {
    ABUYOG: true,
    ALANGALANG: true,
    ALBUERA: true,
    BABATNGON: true,
    BARUGO: true,
    BATO: true,
    'BAYBAY CITY': true,
    BURAUEN: true,
    CALUBIAN: true,
    CAPOOCAN: true,
    CARIGARA: true,
    DAGAMI: true,
    DULAG: true,
    HILONGOS: true,
    HINDANG: true,
    INOPACAN: true,
    ISABEL: true,
    JARO: true,
    'JAVIER (BUGHO)': true,
    JULITA: true,
    KANANGA: true,
    'LA PAZ': true,
    LEYTE: true,
    MACARTHUR: true,
    MAHAPLAG: true,
    'MATAG-OB': true,
    MATALOM: true,
    MAYORGA: true,
    MERIDA: true,
    'ORMOC CITY': true,
    PALO: true,
    PALOMPON: true,
    PASTRANA: true,
    'SAN ISIDRO': true,
    'SAN MIGUEL': true,
    'SANTA FE': true,
    TABANGO: true,
    TABONTABON: true,
    'TACLOBAN CITY': true,
    TANAUAN: true,
    TOLOSA: true,
    TUNGA: true,
    VILLABA: true
  },
  'NORTHERN SAMAR': {
    ALLEN: true,
    BIRI: true,
    BOBON: true,
    CAPUL: true,
    CATARMAN: true,
    CATUBIG: true,
    GAMAY: true,
    LAOANG: true,
    LAPINIG: true,
    'LAS NAVAS': true,
    LAVEZARES: true,
    'LOPE DE VEGA': true,
    MAPANAS: true,
    MONDRAGON: true,
    PALAPAG: true,
    PAMBUJAN: true,
    ROSARIO: true,
    'SAN ANTONIO': true,
    'SAN ISIDRO': true,
    'SAN JOSE': true,
    'SAN ROQUE': true,
    'SAN VICENTE': true,
    'SILVINO LOBOS': true,
    VICTORIA: true
  },
  'SAMAR (WESTERN SAMAR)': {
    ALMAGRO: true,
    BASEY: true,
    'CALBAYOG CITY': true,
    CALBIGA: true,
    'CATBALOGAN CITY': true,
    DARAM: true,
    GANDARA: true,
    HINABANGAN: true,
    JIABONG: true,
    MARABUT: true,
    MATUGUINAO: true,
    MOTIONG: true,
    PAGSANGHAN: true,
    'PARANAS (WRIGHT)': true,
    PINABACDAO: true,
    'SAN JORGE': true,
    'SAN JOSE DE BUAN': true,
    'SAN SEBASTIAN': true,
    'SANTA MARGARITA': true,
    'SANTA RITA': true,
    'SANTO NIÑO': true,
    'TAGAPUL-AN': true,
    TALALORA: true,
    TARANGNAN: true,
    VILLAREAL: true,
    ZUMARRAGA: true
  },
  'SOUTHERN LEYTE': {
    ANAHAWAN: true,
    BONTOC: true,
    HINUNANGAN: true,
    HINUNDAYAN: true,
    LIBAGON: true,
    LILOAN: true,
    LIMASAWA: true,
    'MAASIN CITY': true,
    MACROHON: true,
    MALITBOG: true,
    'PADRE BURGOS': true,
    PINTUYAN: true,
    'SAINT BERNARD': true,
    'SAN FRANCISCO': true,
    'SAN JUAN (CABALIAN)': true,
    'SAN RICARDO': true,
    SILAGO: true,
    SOGOD: true,
    'TOMAS OPPUS': true
  },
  'ZAMBOANGA DEL NORTE': {
    'BACUNGAN (LEON T. POSTIGO)': true,
    BALIGUIAN: true,
    'DAPITAN CITY': true,
    'DIPOLOG CITY': true,
    GODOD: true,
    GUTALAC: true,
    'JOSE DALMAN (PONOT)': true,
    KALAWIT: true,
    KATIPUNAN: true,
    'LA LIBERTAD': true,
    LABASON: true,
    LILOY: true,
    MANUKAN: true,
    MUTIA: true,
    'PIÑAN (NEW PIÑAN)': true,
    POLANCO: true,
    'PRES. MANUEL A. ROXAS': true,
    RIZAL: true,
    SALUG: true,
    'SERGIO OSMEÑA SR.': true,
    SIAYAN: true,
    SIBUCO: true,
    SIBUTAD: true,
    SINDANGAN: true,
    SIOCON: true,
    SIRAWAI: true,
    TAMPILISAN: true
  },
  'ZAMBOANGA DEL SUR': {
    AURORA: true,
    BAYOG: true,
    DIMATALING: true,
    DINAS: true,
    DUMALINAO: true,
    DUMINGAG: true,
    GUIPOS: true,
    JOSEFINA: true,
    KUMALARANG: true,
    LABANGAN: true,
    LAKEWOOD: true,
    LAPUYAN: true,
    MAHAYAG: true,
    MARGOSATUBIG: true,
    MIDSALIP: true,
    MOLAVE: true,
    'PAGADIAN CITY': true,
    PITOGO: true,
    'RAMON MAGSAYSAY (LIARGO)': true,
    'SAN MIGUEL': true,
    'SAN PABLO': true,
    'SOMINOT (DON MARIANO MARCOS)': true,
    TABINA: true,
    TAMBULIG: true,
    TIGBAO: true,
    TUKURAN: true,
    'VINCENZO A. SAGUN': true,
    'ZAMBOANGA CITY': true
  },
  'ZAMBOANGA SIBUGAY': {
    ALICIA: true,
    BUUG: true,
    DIPLAHAN: true,
    IMELDA: true,
    IPIL: true,
    KABASALAN: true,
    MABUHAY: true,
    MALANGAS: true,
    NAGA: true,
    OLUTANGA: true,
    PAYAO: true,
    'ROSELLER LIM': true,
    SIAY: true,
    TALUSAN: true,
    TITAY: true,
    TUNGAWAN: true
  },
  BASILAN: {
    AKBAR: true,
    'AL-BARKA': true,
    'HADJI MOHAMMAD AJUL': true,
    'HADJI MUHTAMAD': true,
    'ISABELA CITY': true,
    'LAMITAN CITY': true,
    LANTAWAN: true,
    MALUSO: true,
    SUMISIP: true,
    'TABUAN-LASA': true,
    'TIPO-TIPO': true,
    TUBURAN: true,
    'UNGKAYA PUKAN': true
  },
  'LANAO DEL SUR': {
    'AMAI MANABILANG (BUMBARAN)': true,
    'BACOLOD-KALAWI (BACOLOD GRANDE)': true,
    BALABAGAN: true,
    'BALINDONG (WATU)': true,
    BAYANG: true,
    BINIDAYAN: true,
    'BUADIPOSO-BUNTONG': true,
    BUBONG: true,
    BUTIG: true,
    CALANOGAS: true,
    'DITSAAN-RAMAIN': true,
    GANASSI: true,
    KAPAI: true,
    KAPATAGAN: true,
    'LUMBA-BAYABAO (MAGUING)': true,
    'LUMBACA-UNAYAN': true,
    LUMBATAN: true,
    LUMBAYANAGUE: true,
    MADALUM: true,
    MADAMBA: true,
    MAGUING: true,
    MALABANG: true,
    MARANTAO: true,
    'MARAWI CITY': true,
    MAROGONG: true,
    MASIU: true,
    MULONDO: true,
    'PAGAYAWAN (TATARIKAN)': true,
    PIAGAPO: true,
    'PICONG (SULTAN GUMANDER)': true,
    'POONA BAYABAO (GATA)': true,
    PUALAS: true,
    SAGUIARAN: true,
    'SULTAN DUMALONDONG': true,
    TAGOLOAN: true,
    TAMPARAN: true,
    TARAKA: true,
    TUBARAN: true,
    TUGAYA: true,
    WAO: true
  },
  MAGUINDANAO: {
    AMPATUAN: true,
    BARIRA: true,
    BULDON: true,
    BULUAN: true,
    'COTABATO CITY': true,
    'DATU ABDULLAH SANGKI': true,
    'DATU ANGGAL MIDTIMBANG': true,
    'DATU BLAH T. SINSUAT': true,
    'DATU HOFFER AMPATUAN': true,
    'DATU ODIN SINSUAT (DINAIG)': true,
    'DATU PAGLAS': true,
    'DATU PIANG': true,
    'DATU SALIBO': true,
    'DATU SAUDI AMPATUAN': true,
    'DATU UNSAY': true,
    'GEN. S. K. PENDATUN': true,
    GUINDULUNGAN: true,
    'KABUNTALAN (TUMBAO)': true,
    MAMASAPANO: true,
    MANGUDADATU: true,
    MATANOG: true,
    'NORTHERN KABUNTALAN': true,
    PAGAGAWAN: true,
    PAGALUNGAN: true,
    PAGLAT: true,
    PANDAG: true,
    PARANG: true,
    'RAJAH BUAYAN': true,
    'SHARIFF AGUAK (MAGANOY)': true,
    'SHARIFF SAYDONA MUSTAPHA': true,
    'SOUTH UPI': true,
    'SULTAN KUDARAT (NULING)': true,
    'SULTAN MASTURA': true,
    'SULTAN SA BARONGIS (LAMBAYONG)': true,
    TALAYAN: true,
    TALITAY: true,
    UPI: true
  },
  SULU: {
    'HADJI PANGLIMA TAHIL (MARUNGGAS)': true,
    INDANAN: true,
    JOLO: true,
    'KALINGALAN CALUANG': true,
    LUGUS: true,
    LUUK: true,
    MAIMBUNG: true,
    'OLD PANAMAO': true,
    OMAR: true,
    PANDAMI: true,
    'PANGLIMA ESTINO (NEW PANAMAO)': true,
    PANGUTARAN: true,
    PARANG: true,
    PATA: true,
    PATIKUL: true,
    SIASI: true,
    TALIPAO: true,
    TAPUL: true,
    TONGKIL: true
  },
  'TAWI-TAWI': {
    BONGAO: true,
    LANGUYAN: true,
    'MAPUN (CAGAYAN DE TAWI-TAWI)': true,
    'PANGLIMA SUGALA (BALIMBING)': true,
    'SAPA-SAPA': true,
    SIBUTU: true,
    SIMUNUL: true,
    SITANGKAI: true,
    'SOUTH UBIAN': true,
    TANDUBAS: true,
    'TURTLE ISLANDS': true
  },
  ABRA: {
    BANGUED: true,
    BOLINEY: true,
    BUCAY: true,
    BUCLOC: true,
    DAGUIOMAN: true,
    DANGLAS: true,
    DOLORES: true,
    'LA PAZ': true,
    LACUB: true,
    LAGANGILANG: true,
    LAGAYAN: true,
    LANGIDEN: true,
    'LICUAN-BAAY (LICUAN)': true,
    LUBA: true,
    MALIBCONG: true,
    MANABO: true,
    PEÑARRUBIA: true,
    PIDIGAN: true,
    PILAR: true,
    SALLAPADAN: true,
    'SAN ISIDRO': true,
    'SAN JUAN': true,
    'SAN QUINTIN': true,
    TAYUM: true,
    TINEG: true,
    TUBO: true,
    VILLAVICIOSA: true
  },
  APAYAO: {
    'CALANASAN (BAYAG)': true,
    CONNER: true,
    FLORA: true,
    KABUGAO: true,
    LUNA: true,
    PUDTOL: true,
    'SANTA MARCELA': true
  },
  BENGUET: {
    ATOK: true,
    'BAGUIO CITY': true,
    BAKUN: true,
    BOKOD: true,
    BUGUIAS: true,
    ITOGON: true,
    KABAYAN: true,
    KAPANGAN: true,
    KIBUNGAN: true,
    'LA TRINIDAD': true,
    MANKAYAN: true,
    SABLAN: true,
    TUBA: true,
    TUBLAY: true
  },
  IFUGAO: {
    AGUINALDO: true,
    'ALFONSO LISTA (POTIA)': true,
    ASIPULO: true,
    BANAUE: true,
    HINGYON: true,
    HUNGDUAN: true,
    KIANGAN: true,
    LAGAWE: true,
    LAMUT: true,
    MAYOYAO: true,
    TINOC: true
  },
  KALINGA: {
    BALBALAN: true,
    LUBUAGAN: true,
    PASIL: true,
    PINUKPUK: true,
    'RIZAL (LIWAN)': true,
    'TABUK CITY': true,
    TANUDAN: true,
    TINGLAYAN: true
  },
  'MOUNTAIN PROVINCE': {
    BARLIG: true,
    BAUKO: true,
    BESAO: true,
    BONTOC: true,
    NATONIN: true,
    PARACELIS: true,
    SABANGAN: true,
    SADANGA: true,
    SAGADA: true,
    TADIAN: true
  },
  'NATIONAL CAPITAL REGION - FOURTH DISTRICT': {
    'CITY OF LAS PIÑAS': true,
    'CITY OF MAKATI': true,
    'CITY OF MUNTINLUPA': true,
    'CITY OF PARAÑAQUE': true,
    'PASAY CITY': true
  },
  'NATIONAL CAPITAL REGION - MANILA': {
    BINONDO: true,
    ERMITA: true,
    INTRAMUROS: true,
    MALATE: true,
    PACO: true,
    PANDACAN: true,
    'PORT AREA': true,
    QUIAPO: true,
    SAMPALOC: true,
    'SAN MIGUEL': true,
    'SAN NICOLAS': true,
    'SANTA ANA': true,
    'SANTA CRUZ': true,
    TONDO: true
  },
  'NATIONAL CAPITAL REGION - SECOND DISTRICT': {
    'CITY OF MANDALUYONG': true,
    'CITY OF MARIKINA': true,
    'CITY OF PASIG': true,
    'QUEZON CITY': true,
    'SAN JUAN CITY': true
  },
  'NATIONAL CAPITAL REGION - THIRD DISTRICT': {
    'CALOOCAN CITY': true,
    'CITY OF VALENZUELA': true,
    'MALABON CITY': true,
    'NAVOTAS CITY': true
  },
  'TAGUIG - PATEROS': { PATEROS: true, TAGUIG: true }
}
