'use strict'

module.exports = {
  TYPES: {
    NEW_EVENT_ROLE: 'NEW_EVENT_ROLE',
    EXPIRING_INVENTORY_ITEM: 'EXPIRING_INVENTORY_ITEM',
    EVENT_VOLUNTEERS_NEEDED: 'EVENT_VOLUNTEERS_NEEDED',
    EVENT_INVITATION: 'EVENT_INVITATION'
  },
}
